version: '3.9'

services:
  headscale:
    image: headscale/headscale:latest
    pull_policy: always
    container_name: headscale
    restart: unless-stopped
    command: headscale serve
    networks:
      - frontend
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
      
secrets:
  # Traefik
  cf_email:
    file: ./.secrets/cf_email
  cf_api_key:
    file: ./.secrets/cf_api_key
  # Authelia
  authelia_jwt_secret:
    file: ./.secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ./.secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: ./.secrets/authelia_storage_encryption_key
  # authelia_duo_api_integration_key:
  #   file: ./.secrets/authelia_duo_api_integration_key
  # authelia_duo_api_secret_key:
  #   file: ./.secrets/authelia_duo_api_secret_key
