version: '3.9'

services:
  headscale:
    image: headscale/headscale:latest
    pull_policy: always
    container_name: headscale
    restart: unless-stopped
    command: headscale serve
    networks:
      - frontend
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.headscale-rtr.rule=PathPrefix(`/`) && Host(`hs.yourdomain.com`)"
      - "traefik.http.services.headscale-svc.loadbalancer.server.port=8080"
      - "traefik.docker.network=frontend"

  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    pull_policy: always
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - frontend
    labels:
      # My normal config
      - "traefik.enable=true"
      - "traefik.http.routers.headscale-ui-rtr.rule=PathPrefix(`/web`) && Host(`hs.yourdomain.com`)"
      - "traefik.http.services.headscale-ui-srv.loadbalancer.server.port=80"
      - "treafik.docker.network=frontend"
      - "traefik.http.routers.headscale-ui-rtr.middlewares=authelia@docker"

  traefik:
    image: traefik:v2.10.4@sha256:57b2516b7549c4f59531bb09311a54a05af237670676529249c3c0b8e58ad0f3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    secrets:
      - cf_email
      - cf_api_key
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cf_email
      - CF_API_KEY_FILE=/run/secrets/cf_api_key
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json

  authelia:
    image: authelia/authelia:4.37.5@sha256:82831059ce5c1151d4ccd37f803cdf35fccbd488c80fe7f9f8de6b76adf40447
    container_name: authelia
    user: 1000:1000
    volumes:
      - ./authelia:/config
    networks:
      - frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.yourdomain.com`)'
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.tls=true'
      - "traefik.http.routers.authelia-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.authelia-secure.tls.domains[0].main=auth.yourdomain.com"
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.yourdomain.com%2F'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
      - "traefik.docker.network=frontend"
    restart: unless-stopped
    environment:
      TZ: America/Denver
      AUTHELIA_JWT_SECRET_FILE: /run/secrets/authelia_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/secrets/authelia_session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/secrets/authelia_storage_encryption_key
      # AUTHELIA_DUO_API_INTEGRATION_KEY_FILE: /run/secrets/authelia_duo_api_integration_key
      # AUTHELIA_DUO_API_SECRET_KEY_FILE: /run/secrets/authelia_duo_api_secret_key
      # AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /run/secrets/authelia_smtp_password
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
      # - authelia_smtp_password
      # - authelia_duo_api_integration_key
      # - authelia_duo_api_secret_key

networks:
  frontend:
    external: true

secrets:
  # Traefik
  cf_email:
    file: ./.secrets/cf_email
  cf_api_key:
    file: ./.secrets/cf_api_key
  # Authelia
  authelia_jwt_secret:
    file: ./.secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ./.secrets/authelia_session_secret
  authelia_storage_encryption_key:
    file: ./.secrets/authelia_storage_encryption_key
  # authelia_duo_api_integration_key:
  #   file: ./.secrets/authelia_duo_api_integration_key
  # authelia_duo_api_secret_key:
  #   file: ./.secrets/authelia_duo_api_secret_key
