services:
  headscale:
    image: headscale/headscale:latest
    pull_policy: always
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - ./headscale/config:/etc/headscale:rw
      - ./headscale/data:/var/lib/headscale:rw
  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: headplane
    restart: unless-stopped
    ports:
      - '3005:3000'
    volumes:
      - './configs/headplane/config.yaml:/etc/headplane/config.yaml:rw'
      - './configs/headscale/config.yaml:/etc/headscale/config.yaml:rw'
      - './data/headplane:/var/lib/headplane:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
