###############################################################
#                   Authelia configuration                    #
###############################################################

theme: dark

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
#jwt_secret: 
default_redirection_url: https://auth.yourdomain.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

# duo_api:
#   disable: false
#   hostname: api-6bd54087.duosecurity.com
#   enable_self_enrollment: false

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  
authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true

access_control:
  default_policy: deny
  rules:
    - domain: 'hs.yourdomain.com'
      policy: one_factor
      resources:
        - '^/web$'
        - '^/web'


session:
  name: authelia_session
  domain: yourdomain.com  # Should match whatever your root protected domain is
  expiration: 3600  # 1 hour
  inactivity: 1800  # 30 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

# identity_providers:
#   oidc:
#     issuer_private_key: |

#     access_token_lifespan: 1h
#     authorize_code_lifespan: 1m
#     id_token_lifespan: 1h
#     refresh_token_lifespan: 90m
#     enable_client_debug_messages: true
#     enforce_pkce: public_clients_only
#     cors:
#       endpoints:
#         - authorization
#         - token
#         - revocation
#         - introspection
#       allowed_origins_from_client_redirect_uris: false
#     clients:
#       - id: zP5EQnctz7TxGgMBh5QnjnuYHciCqjnx
#         description: Headscale
#         secret: '$argon2id$v=19$m=65536,t=3,p=4$nwWpeMaKqg6nl/7XNjx4yw$3Sgn8oaSpkybBtoKCOetyW6hKmbOCJK5cTw7RVr/bm4'
#         public: false
#         authorization_policy: one_factor
#         redirect_uris:
#           - https://hs.yourdomain.com/a/oauth_response
#         scopes:
#           - openid
#           - profile
#           - email
#         userinfo_signing_algorithm: none  

